FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

COPY . .

RUN rm -rf node_modules

RUN npm install --legacy-peer-deps

ENV NODE_ENV=production
ENV PORT=5000

EXPOSE 5000

CMD ["node", "src/server.js"]
